font_family      JetBrainsMono Nerd Font
font_size        13.0

# top right bottom left
window_padding_width 5 5 5 10

dynamic_padding yes

foreground        #CCCCCC
background        #111111

cursor            #993333
cursor_text_color #111111
cursor_shape      beam
cursor_blink      yes

# Use Ctrl+C / Ctrl+V for copy-paste
#map ctrl+c copy_to_clipboard
#map ctrl+v paste_from_clipboard

# Optional: keep Shift variants working too
map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard

# Right-click to paste from clipboard (Ctrl+C copies go here)
mouse_map right press ungrabbed paste_from_clipboard
